// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.Migrations
{
    [DbContext(typeof(ObraContext))]
    [Migration("20240221195348_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"), 1L, 1);

                    b.Property<int>("NumAsiento")
                        .HasColumnType("int");

                    b.Property<bool>("Reservado")
                        .HasColumnType("bit");

                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AsientoId");

                    b.HasIndex("SesionId");

                    b.HasIndex("UserId");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("BackEnd.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            Descripcion = "Descripcion 1",
                            Genero = "Drama",
                            Imagen = "ruta imagen 1",
                            Titulo = "Obra 1"
                        },
                        new
                        {
                            ObraId = 2,
                            Descripcion = "Descripcion 2",
                            Genero = "Comedia",
                            Imagen = "ruta imagen 2",
                            Titulo = "Obra 2"
                        },
                        new
                        {
                            ObraId = 3,
                            Descripcion = "Descripcion 3",
                            Genero = "Suspense",
                            Imagen = "ruta imagen 3",
                            Titulo = "Obra 3"
                        },
                        new
                        {
                            ObraId = 4,
                            Descripcion = "Descripcion 4",
                            Genero = "Suspense",
                            Imagen = "ruta imagen 4",
                            Titulo = "Obra 4"
                        },
                        new
                        {
                            ObraId = 5,
                            Descripcion = "Descripcion 5",
                            Genero = "Drama",
                            Imagen = "ruta imagen 5",
                            Titulo = "Obra 5"
                        },
                        new
                        {
                            ObraId = 6,
                            Descripcion = "Descripcion 6",
                            Genero = "Comedia",
                            Imagen = "ruta imagen 6",
                            Titulo = "Obra 6"
                        },
                        new
                        {
                            ObraId = 7,
                            Descripcion = "Descripcion 7",
                            Genero = "Comedia",
                            Imagen = "ruta imagen 7",
                            Titulo = "Obra 7"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"), 1L, 1);

                    b.Property<DateTime>("DiaSesion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraSesion")
                        .HasColumnType("time");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("ObraId");

                    b.ToTable("Sesiones");

                    b.HasData(
                        new
                        {
                            SesionId = 1,
                            DiaSesion = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSesion = new TimeSpan(0, 20, 30, 0, 0),
                            ObraId = 1
                        });
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BackEnd.Models.Asiento", b =>
                {
                    b.HasOne("BackEnd.Models.Sesion", "Sesion")
                        .WithMany("Asientos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.User", "User")
                        .WithMany("Asientos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.HasOne("BackEnd.Models.Obra", "Obra")
                        .WithMany("Sesiones")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("BackEnd.Models.Obra", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Navigation("Asientos");
                });
#pragma warning restore 612, 618
        }
    }
}
