// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.Migrations
{
    [DbContext(typeof(ObraContext))]
    [Migration("20240317210506_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackEnd.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"), 1L, 1);

                    b.Property<int>("Num_Asiento")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<bool>("Reservado")
                        .HasColumnType("bit");

                    b.Property<int?>("SesionId")
                        .HasColumnType("int");

                    b.HasKey("AsientoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("SesionId");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            AsientoId = 1,
                            Num_Asiento = 1,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 2,
                            Num_Asiento = 2,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 3,
                            Num_Asiento = 3,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 4,
                            Num_Asiento = 4,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 5,
                            Num_Asiento = 5,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 6,
                            Num_Asiento = 6,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 7,
                            Num_Asiento = 7,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 8,
                            Num_Asiento = 8,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 9,
                            Num_Asiento = 9,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 10,
                            Num_Asiento = 10,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 11,
                            Num_Asiento = 11,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 12,
                            Num_Asiento = 12,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 13,
                            Num_Asiento = 13,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 14,
                            Num_Asiento = 14,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 15,
                            Num_Asiento = 15,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 16,
                            Num_Asiento = 16,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 17,
                            Num_Asiento = 17,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 18,
                            Num_Asiento = 18,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 19,
                            Num_Asiento = 19,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 20,
                            Num_Asiento = 20,
                            ObraId = 1,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 21,
                            Num_Asiento = 1,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 22,
                            Num_Asiento = 2,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 23,
                            Num_Asiento = 3,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 24,
                            Num_Asiento = 4,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 25,
                            Num_Asiento = 5,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 26,
                            Num_Asiento = 6,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 27,
                            Num_Asiento = 7,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 28,
                            Num_Asiento = 8,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 29,
                            Num_Asiento = 9,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 30,
                            Num_Asiento = 10,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 31,
                            Num_Asiento = 11,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 32,
                            Num_Asiento = 12,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 33,
                            Num_Asiento = 13,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 34,
                            Num_Asiento = 14,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 35,
                            Num_Asiento = 15,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 36,
                            Num_Asiento = 16,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 37,
                            Num_Asiento = 17,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 38,
                            Num_Asiento = 18,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 39,
                            Num_Asiento = 19,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 40,
                            Num_Asiento = 20,
                            ObraId = 2,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 41,
                            Num_Asiento = 1,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 42,
                            Num_Asiento = 2,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 43,
                            Num_Asiento = 3,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 44,
                            Num_Asiento = 4,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 45,
                            Num_Asiento = 5,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 46,
                            Num_Asiento = 6,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 47,
                            Num_Asiento = 7,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 48,
                            Num_Asiento = 8,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 49,
                            Num_Asiento = 9,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 50,
                            Num_Asiento = 10,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 51,
                            Num_Asiento = 11,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 52,
                            Num_Asiento = 12,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 53,
                            Num_Asiento = 13,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 54,
                            Num_Asiento = 14,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 55,
                            Num_Asiento = 15,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 56,
                            Num_Asiento = 16,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 57,
                            Num_Asiento = 17,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 58,
                            Num_Asiento = 18,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 59,
                            Num_Asiento = 19,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 60,
                            Num_Asiento = 20,
                            ObraId = 3,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 61,
                            Num_Asiento = 1,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 62,
                            Num_Asiento = 2,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 63,
                            Num_Asiento = 3,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 64,
                            Num_Asiento = 4,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 65,
                            Num_Asiento = 5,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 66,
                            Num_Asiento = 6,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 67,
                            Num_Asiento = 7,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 68,
                            Num_Asiento = 8,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 69,
                            Num_Asiento = 9,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 70,
                            Num_Asiento = 10,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 71,
                            Num_Asiento = 11,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 72,
                            Num_Asiento = 12,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 73,
                            Num_Asiento = 13,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 74,
                            Num_Asiento = 14,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 75,
                            Num_Asiento = 15,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 76,
                            Num_Asiento = 16,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 77,
                            Num_Asiento = 17,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 78,
                            Num_Asiento = 18,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 79,
                            Num_Asiento = 19,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 80,
                            Num_Asiento = 20,
                            ObraId = 4,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 81,
                            Num_Asiento = 1,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 82,
                            Num_Asiento = 2,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 83,
                            Num_Asiento = 3,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 84,
                            Num_Asiento = 4,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 85,
                            Num_Asiento = 5,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 86,
                            Num_Asiento = 6,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 87,
                            Num_Asiento = 7,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 88,
                            Num_Asiento = 8,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 89,
                            Num_Asiento = 9,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 90,
                            Num_Asiento = 10,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 91,
                            Num_Asiento = 11,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 92,
                            Num_Asiento = 12,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 93,
                            Num_Asiento = 13,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 94,
                            Num_Asiento = 14,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 95,
                            Num_Asiento = 15,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 96,
                            Num_Asiento = 16,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 97,
                            Num_Asiento = 17,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 98,
                            Num_Asiento = 18,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 99,
                            Num_Asiento = 19,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 100,
                            Num_Asiento = 20,
                            ObraId = 5,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 101,
                            Num_Asiento = 1,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 102,
                            Num_Asiento = 2,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 103,
                            Num_Asiento = 3,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 104,
                            Num_Asiento = 4,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 105,
                            Num_Asiento = 5,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 106,
                            Num_Asiento = 6,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 107,
                            Num_Asiento = 7,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 108,
                            Num_Asiento = 8,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 109,
                            Num_Asiento = 9,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 110,
                            Num_Asiento = 10,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 111,
                            Num_Asiento = 11,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 112,
                            Num_Asiento = 12,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 113,
                            Num_Asiento = 13,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 114,
                            Num_Asiento = 14,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 115,
                            Num_Asiento = 15,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 116,
                            Num_Asiento = 16,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 117,
                            Num_Asiento = 17,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 118,
                            Num_Asiento = 18,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 119,
                            Num_Asiento = 19,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 120,
                            Num_Asiento = 20,
                            ObraId = 6,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 121,
                            Num_Asiento = 1,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 122,
                            Num_Asiento = 2,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 123,
                            Num_Asiento = 3,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 124,
                            Num_Asiento = 4,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 125,
                            Num_Asiento = 5,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 126,
                            Num_Asiento = 6,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 127,
                            Num_Asiento = 7,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 128,
                            Num_Asiento = 8,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 129,
                            Num_Asiento = 9,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 130,
                            Num_Asiento = 10,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 131,
                            Num_Asiento = 11,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 132,
                            Num_Asiento = 12,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 133,
                            Num_Asiento = 13,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 134,
                            Num_Asiento = 14,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 135,
                            Num_Asiento = 15,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 136,
                            Num_Asiento = 16,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 137,
                            Num_Asiento = 17,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 138,
                            Num_Asiento = 18,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 139,
                            Num_Asiento = 19,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 140,
                            Num_Asiento = 20,
                            ObraId = 7,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 141,
                            Num_Asiento = 1,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 142,
                            Num_Asiento = 2,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 143,
                            Num_Asiento = 3,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 144,
                            Num_Asiento = 4,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 145,
                            Num_Asiento = 5,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 146,
                            Num_Asiento = 6,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 147,
                            Num_Asiento = 7,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 148,
                            Num_Asiento = 8,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 149,
                            Num_Asiento = 9,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 150,
                            Num_Asiento = 10,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 151,
                            Num_Asiento = 11,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 152,
                            Num_Asiento = 12,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 153,
                            Num_Asiento = 13,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 154,
                            Num_Asiento = 14,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 155,
                            Num_Asiento = 15,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 156,
                            Num_Asiento = 16,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 157,
                            Num_Asiento = 17,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 158,
                            Num_Asiento = 18,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 159,
                            Num_Asiento = 19,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 160,
                            Num_Asiento = 20,
                            ObraId = 8,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 161,
                            Num_Asiento = 1,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 162,
                            Num_Asiento = 2,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 163,
                            Num_Asiento = 3,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 164,
                            Num_Asiento = 4,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 165,
                            Num_Asiento = 5,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 166,
                            Num_Asiento = 6,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 167,
                            Num_Asiento = 7,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 168,
                            Num_Asiento = 8,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 169,
                            Num_Asiento = 9,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 170,
                            Num_Asiento = 10,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 171,
                            Num_Asiento = 11,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 172,
                            Num_Asiento = 12,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 173,
                            Num_Asiento = 13,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 174,
                            Num_Asiento = 14,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 175,
                            Num_Asiento = 15,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 176,
                            Num_Asiento = 16,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 177,
                            Num_Asiento = 17,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 178,
                            Num_Asiento = 18,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 179,
                            Num_Asiento = 19,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 180,
                            Num_Asiento = 20,
                            ObraId = 9,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 181,
                            Num_Asiento = 1,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 182,
                            Num_Asiento = 2,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 183,
                            Num_Asiento = 3,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 184,
                            Num_Asiento = 4,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 185,
                            Num_Asiento = 5,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 186,
                            Num_Asiento = 6,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 187,
                            Num_Asiento = 7,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 188,
                            Num_Asiento = 8,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 189,
                            Num_Asiento = 9,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 190,
                            Num_Asiento = 10,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 191,
                            Num_Asiento = 11,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 192,
                            Num_Asiento = 12,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 193,
                            Num_Asiento = 13,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 194,
                            Num_Asiento = 14,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 195,
                            Num_Asiento = 15,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 196,
                            Num_Asiento = 16,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 197,
                            Num_Asiento = 17,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 198,
                            Num_Asiento = 18,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 199,
                            Num_Asiento = 19,
                            ObraId = 10,
                            Reservado = false
                        },
                        new
                        {
                            AsientoId = 200,
                            Num_Asiento = 20,
                            ObraId = 10,
                            Reservado = false
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Estreno", b =>
                {
                    b.Property<int>("EstrenoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstrenoId"), 1L, 1);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstrenoId");

                    b.ToTable("Estrenos");

                    b.HasData(
                        new
                        {
                            EstrenoId = 1,
                            Imagen = "popins.jpg",
                            Titulo = "Mary Poppins"
                        },
                        new
                        {
                            EstrenoId = 2,
                            Imagen = "celes.png",
                            Titulo = "La Celestina"
                        },
                        new
                        {
                            EstrenoId = 3,
                            Imagen = "bodas.png",
                            Titulo = "Bodas de sangre"
                        },
                        new
                        {
                            EstrenoId = 4,
                            Imagen = "coldplay.png",
                            Titulo = "Tributo a coldplay"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Estreno_1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Estreno_2")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interpretes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int>("Sala")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Valoracion")
                        .HasColumnType("int");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");

                    b.HasData(
                        new
                        {
                            ObraId = 1,
                            Descripcion = "Una obra de Shakespeare.",
                            Director = "Andres Torres",
                            Duracion = "120 mins",
                            Fecha = new DateTime(2024, 3, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 8, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 5, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Drama",
                            Imagen = "hamlet.jpg",
                            Interpretes = "A.Torres, Cristian, Pablo.Pe, Ricardon, Albertos & Sofía",
                            Precio = 30,
                            Sala = 1,
                            Titulo = "Hamlet",
                            Valoracion = 4
                        },
                        new
                        {
                            ObraId = 2,
                            Descripcion = "Un musical épico.",
                            Director = "Mutombo Martinez",
                            Duracion = "150 mins",
                            Fecha = new DateTime(2024, 3, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 15, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 7, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Musical",
                            Imagen = "leon.png",
                            Interpretes = "Marta Soler, Luis Gomez, Ana Páez, Mario Ruiz",
                            Precio = 25,
                            Sala = 2,
                            Titulo = "El Rey León",
                            Valoracion = 5
                        },
                        new
                        {
                            ObraId = 3,
                            Descripcion = "El clásico de Shakespeare sobre dos amantes desafortunados.",
                            Director = "Carlos Vidal",
                            Duracion = "130 mins",
                            Fecha = new DateTime(2024, 3, 19, 22, 15, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 9, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 5, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Tragedia",
                            Imagen = "romeo.png",
                            Interpretes = "Elena Nuñez, Jorge Sanz",
                            Precio = 20,
                            Sala = 3,
                            Titulo = "Romeo y Julieta",
                            Valoracion = 4
                        },
                        new
                        {
                            ObraId = 4,
                            Descripcion = "Una representación intensa de la obra maestra de Federico García Lorca.",
                            Director = "Irene Moya",
                            Duracion = "90 mins",
                            Fecha = new DateTime(2024, 3, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 12, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 8, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Drama",
                            Imagen = "casa.png",
                            Interpretes = "Carmen Linares, Pilar Tena, Laura Ortega",
                            Precio = 30,
                            Sala = 4,
                            Titulo = "La Casa de Bernarda Alba",
                            Valoracion = 5
                        },
                        new
                        {
                            ObraId = 5,
                            Descripcion = "Una obra clásica española, llena de romance y aventura.",
                            Director = "Roberto Gómez",
                            Duracion = "110 mins",
                            Fecha = new DateTime(2024, 3, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 16, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 17, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Drama",
                            Imagen = "juan.png",
                            Interpretes = "Juan Martínez, Clara Ros, Miguel Ángel Jiménez",
                            Precio = 20,
                            Sala = 3,
                            Titulo = "Don Juan Tenorio",
                            Valoracion = 2
                        },
                        new
                        {
                            ObraId = 6,
                            Descripcion = "El famoso musical de Andrew Lloyd Webber que ha encantado a audiencias de todo el mundo.",
                            Director = "Mónica García",
                            Duracion = "140 mins",
                            Fecha = new DateTime(2024, 3, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 18, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 8, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Musical",
                            Imagen = "cats.png",
                            Interpretes = "Ana Belén, Luis Fonsi, Rosalía Vila",
                            Precio = 25,
                            Sala = 1,
                            Titulo = "Cats",
                            Valoracion = 5
                        },
                        new
                        {
                            ObraId = 7,
                            Descripcion = "Un épico musical basado en la novela de Victor Hugo.",
                            Director = "Jaime Costa",
                            Duracion = "165 mins",
                            Fecha = new DateTime(2024, 3, 22, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 15, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 7, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Musical",
                            Imagen = "mise.png",
                            Interpretes = "Pedro Fernández, Diana Navarro, Sergio Dalma",
                            Precio = 25,
                            Sala = 3,
                            Titulo = "Les Misérables",
                            Valoracion = 3
                        },
                        new
                        {
                            ObraId = 8,
                            Descripcion = "Una de las últimas obras maestras de Shakespeare, llena de magia y misterio.",
                            Director = "Lucía Hernández",
                            Duracion = "135 mins",
                            Fecha = new DateTime(2024, 3, 23, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 20, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 14, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Comedia",
                            Imagen = "tempes.png",
                            Interpretes = "Carlos Sánchez, Marta Rivera, Daniel López",
                            Precio = 20,
                            Sala = 3,
                            Titulo = "La Tempestad",
                            Valoracion = 4
                        },
                        new
                        {
                            ObraId = 9,
                            Descripcion = "El clásico musical inspirado en Romeo y Julieta, ambientado en Nueva York de los años 50.",
                            Director = "Roberto Álvarez",
                            Duracion = "160 mins",
                            Fecha = new DateTime(2024, 3, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 16, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 17, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Musical",
                            Imagen = "west.png",
                            Interpretes = "Ángela Ponce, Miguel Torres, Laura Jiménez",
                            Precio = 25,
                            Sala = 3,
                            Titulo = "West Side Story",
                            Valoracion = 3
                        },
                        new
                        {
                            ObraId = 10,
                            Descripcion = "Un espectacular musical basado en la novela de Gaston Leroux.",
                            Director = "Sofía Martín",
                            Duracion = "150 mins",
                            Fecha = new DateTime(2024, 3, 21, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_1 = new DateTime(2024, 4, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Fecha_Estreno_2 = new DateTime(2024, 5, 28, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Drama",
                            Imagen = "fastas.png",
                            Interpretes = "Javier Gómez, Raquel del Pozo, Mario Casas",
                            Precio = 30,
                            Sala = 4,
                            Titulo = "Phantom of the Opera",
                            Valoracion = 5
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"), 1L, 1);

                    b.Property<DateTime>("DiaSesion")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraSesion")
                        .HasColumnType("time");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("ObraId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Password = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user1@gmail.com",
                            Name = "User1",
                            Password = "user1"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Asiento", b =>
                {
                    b.HasOne("BackEnd.Models.Obra", "Obra")
                        .WithMany("Asientos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Sesion", null)
                        .WithMany("Asientos")
                        .HasForeignKey("SesionId");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.HasOne("BackEnd.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("BackEnd.Models.Obra", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("BackEnd.Models.Sesion", b =>
                {
                    b.Navigation("Asientos");
                });
#pragma warning restore 612, 618
        }
    }
}
